graphical improvements
tkjantti/13thGuy pull request #2
Opened 2024-09-29 16:35 UTC by sz1521

- fix not updating first screen
- add crt effect as global
- add opacity effect to go
- keep controls info on ready, steady
- less brightness for pseudo 3d shadow

2024-09-29 16:37 UTC, sz1521 commented on src/game.ts
> -    cx.filter = "grayscale(1) brightness(0.6)";
This was slow on start up screen

2024-09-29 16:38 UTC, sz1521 commented on src/Level.ts
> +                .replace(")", ",0.3)");
Maybe more clear what is actual trackelement and what not

2024-10-01 04:01 UTC, tkjantti requested changes

2024-10-01 04:01 UTC, tkjantti commented on src/game.ts
> +                    (textAnimationCounter++ % 60 === 0 ? "ㅤ" : "▮"),
This repeating part could be in a subroutine.

2024-10-01 04:02 UTC, tkjantti approved these changes

2024-10-01 06:01 UTC, sz1521 commented on src/game.ts
> +        setState(GameState.Init);
Yes, I think it was not working back for some reaso without that time but might been just hurry to get it done. I will try again witth this.

2024-10-01 17:40 UTC, merged